-- Insetions de n-uplets de test

CREATE SEQUENCE SeqClient;
CREATE SEQUENCE SeqTable;
CREATE SEQUENCE SeqReservation;
CREATE SEQUENCE SeqCarte;


-- Creation des tables
-- 3 tables exterieures
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'EXTERIEUR');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'EXTERIEUR');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'EXTERIEUR');
-- 4 tables coté fenêtre
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 6, 5, 4, 'FENETRE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 6, 5, 4, 'FENETRE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'FENETRE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'FENETRE');
-- 5 tables coté cuisine
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 6, 5, 4, 'CUISINE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 4, 4, 4, 'CUISINE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 4, 4, 4, 'CUISINE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'CUISINE');
INSERT INTO TableRepas
	VALUES (SeqTable.nextval, 2, 2, 2, 'CUISINE');



-- Creation de clients
INSERT INTO Client
	VALUES (SeqClient.nextval, 'ARNAUD', '0607080910');
INSERT INTO Client
	VALUES (SeqClient.nextval, 'CLEMENT', '0000000000');
INSERT INTO Client
	VALUES (SeqClient.nextval, 'FLORENT', '0123456789');
INSERT INTO Client
	VALUES (SeqClient.nextval, 'FLORIAN', '0605040302');
INSERT INTO Client
	VALUES (SeqClient.nextval, 'IAGO', '0987654321');
INSERT INTO Client
	VALUES (SeqClient.nextval, 'NICOLAS', '0102030405');



-- Creation de cartes
INSERT INTO Carte
	VALUES (SeqCarte.nextval);
INSERT INTO Carte
	VALUES (SeqCarte.nextval);
INSERT INTO Carte
	VALUES (SeqCarte.nextval);



-- Creation d'articles
-- Boissons
-- Sodas
INSERT INTO Article
	VALUES ('COCA', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('ORANGINA', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('ICE TEA', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('FANTA', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('DIABOLO', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('SPRITE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('JUS DE FRUIT', 'BOISSON', 'AUCUNE');
-- Eaux
INSERT INTO Article
	VALUES ('VALS', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('ARCENS', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('SAN PELLEGRINO', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('PERRIER', 'BOISSON', 'AUCUNE');
-- Aperos
INSERT INTO Article
	VALUES ('KIR', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('KIR ROYAL', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('MOJITO', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('WHISKY', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('COCKTAIL MAISON', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('COCKTAIL SANS ALCOOL', 'BOISSON', 'AUCUNE');
-- Vins
INSERT INTO Article
	VALUES ('SANTENAY', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('GIVRY', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('CAIRANNE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('CORNAS', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('CROZES-HERMITAGE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('BOURGOGNE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('RIVESALTES', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('SAUTERNES', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('MONBAZILLAC', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('ALSACE', 'BOISSON', 'AUCUNE');
-- Autres
INSERT INTO Article
	VALUES ('CAFE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('BIERE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('CIDRE', 'BOISSON', 'AUCUNE');
INSERT INTO Article
	VALUES ('CLAIRETTE', 'BOISSON', 'ARDECHE');
INSERT INTO Article
	VALUES ('DIGESTIF', 'BOISSON', 'AUCUNE');

-- Menus
INSERT INTO Article
	VALUES ('MENU ECUME DE MER', 'MENU', 'MER');
INSERT INTO Article
	VALUES ('MENU AU COIN DU FEU', 'MENU', 'ARDECHE');
INSERT INTO Article
	VALUES ('MENU ENFANT', 'MENU', 'AUCUNE');

-- Entrees
INSERT INTO Article
	VALUES ('SALADE RAVIOLES', 'ENTREE', 'ARDECHE');
INSERT INTO Article
	VALUES ('SALADE CAILLETTE', 'ENTREE', 'ARDECHE');
INSERT INTO Article
	VALUES ('TERRINE DE LAPIN', 'ENTREE', 'ARDECHE');
INSERT INTO Article
	VALUES ('FEUILLETE D ESCARGOTS', 'ENTREE', 'ARDECHE');
INSERT INTO Article
	VALUES ('VELOUTE DE CHAMPIGNONS', 'ENTREE', 'ARDECHE');
INSERT INTO Article
	VALUES ('SALADE DE POULPE', 'ENTREE', 'MER');
INSERT INTO Article
	VALUES ('SALADE ST JACQUES', 'ENTREE', 'MER');
INSERT INTO Article
	VALUES ('SAUMON MARINE', 'ENTREE', 'MER');
INSERT INTO Article
	VALUES ('AVOCAT SAUMON FUME', 'ENTREE', 'MER');
INSERT INTO Article
	VALUES ('TERRINE DE LA MER', 'ENTREE', 'MER');
INSERT INTO Article
	VALUES ('TARTARE DE SAUMON ET AGRUMES', 'ENTREE', 'MER');
INSERT INTO Article
	VALUES ('SALADE CESAR', 'ENTREE', 'AUCUNE');
INSERT INTO Article
	VALUES ('TRILOGIE DE POIVRONS ET CHEVRE', 'ENTREE', 'AUCUNE');
INSERT INTO Article
	VALUES ('CREME DE BETTERAVES', 'ENTREE', 'AUCUNE');
INSERT INTO Article
	VALUES ('FOIE GRAS', 'ENTREE', 'AUCUNE');
INSERT INTO Article
	VALUES ('VELOUTE DE CAROTTES AU CUMIN', 'ENTREE', 'AUCUNE');
INSERT INTO Article
	VALUES ('TATIN D AUBERGINES', 'ENTREE', 'AUCUNE');

-- Plats
INSERT INTO Article
	VALUES ('CIVET SANGLIER', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('TRUITE AUX AMANDES', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('GRATIN RAVIOLES', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('GRATIN DAUPHINOIS AUX CHAMPIGNONS', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('SALADE COMPLETE', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('CUISSE DE GRENOUILLES', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('DINDE AUX CHATAIGNES', 'PLAT', 'ARDECHE');
INSERT INTO Article
	VALUES ('PAVET CABILLAUD', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('MOULES FRITES', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('FILET DE ROUGET ET PETITS LEGUMES', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('STEAK DE THON', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('PETITE FRITURE', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('ASPERGES ET COQUILLAGES', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('LOTTE A L ARMORICAINE', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('MAQUERAU AU VIN BLANC', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('GRATTIN DE COUTEAUX AU QUINOA', 'PLAT', 'MER');
INSERT INTO Article
	VALUES ('STEAK FRITES', 'PLAT', 'AUCUNE');
INSERT INTO Article
	VALUES ('PIZZA VEGETARIENNE', 'PLAT', 'AUCUNE');
INSERT INTO Article
	VALUES ('BURGER MAISON', 'PLAT', 'AUCUNE');
INSERT INTO Article
	VALUES ('TARTIFLETTE', 'PLAT', 'AUCUNE');
INSERT INTO Article
	VALUES ('LASAGNES', 'PLAT', 'AUCUNE');

--Desserts
INSERT INTO Article
	VALUES ('MARRONS GLACES', 'DESSERT', 'ARDECHE');
INSERT INTO Article
	VALUES ('ASSIETTE DE FROMAGES', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('PROFITEROLES AU CHOCOLAT', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('COUPE GLACEE', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('SALADE DE FRUITS', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('ILE FLOTTANTE', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('CRUMBLE AUX POIRES', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('TIRAMISU AUX SPECULOS', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('TARTE AU CITRON MERINGUEE', 'DESSERT', 'AUCUNE');
INSERT INTO Article
	VALUES ('CAFE GOURMAND', 'BOISSON', 'AUCUNE');



-- Creation de services
INSERT INTO Service
	VALUES (to_date('2016-04-16', 'YYYY-MM-DD'), 'MIDI', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-16', 'YYYY-MM-DD'), 'SOIR', 3);
INSERT INTO Service
	VALUES (to_date('2016-04-18', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-18', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-19', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-19', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-20', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-20', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-21', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-21', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-22', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-22', 'YYYY-MM-DD'), 'SOIR', 3);
INSERT INTO Service
	VALUES (to_date('2016-04-23', 'YYYY-MM-DD'), 'MIDI', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-23', 'YYYY-MM-DD'), 'SOIR', 3);
INSERT INTO Service
	VALUES (to_date('2016-04-25', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-25', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-26', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-26', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-27', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-27', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-28', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-28', 'YYYY-MM-DD'), 'SOIR', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-29', 'YYYY-MM-DD'), 'MIDI', 1);
INSERT INTO Service
	VALUES (to_date('2016-04-29', 'YYYY-MM-DD'), 'SOIR', 3);
INSERT INTO Service
	VALUES (to_date('2016-04-30', 'YYYY-MM-DD'), 'MIDI', 2);
INSERT INTO Service
	VALUES (to_date('2016-04-30', 'YYYY-MM-DD'), 'SOIR', 3);


-- Creation de reservations
INSERT INTO Reservation
	VALUES (SeqReservation.nextval, 2, 20, 00, 5, to_date('2016-04-16', 'YYYY-MM-DD'), 'SOIR');
INSERT INTO Reservation
	VALUES (SeqReservation.nextval, 2, 20, 00, 2, to_date('2016-04-30', 'YYYY-MM-DD'), 'SOIR');
INSERT INTO Reservation
	VALUES (SeqReservation.nextval, 5, 20, 00, 4, to_date('2016-04-30', 'YYYY-MM-DD'), 'SOIR');
INSERT INTO Reservation
	VALUES (SeqReservation.nextVal, 8, 12, 30, 1, to_date('2016-04-30', 'YYYY-MM-DD'), 'MIDI');
INSERT INTO Reservation
	VALUES (SeqReservation.nextval, 1, 20, 00, 6, to_date('2016-04-27', 'YYYY-MM-DD'), 'SOIR');


-- Creation de occupe
INSERT INTO Occupe
	VALUES (1, 3);
INSERT INTO Occupe
	VALUES (2, 1);
INSERT INTO Occupe
	VALUES (3, 4);
INSERT INTO Occupe
	VALUES (4, 9);
INSERT INTO Occupe
	VALUES (4, 10);
INSERT INTO Occupe
	VALUES (5, 12);



-- Creation de Coute
INSERT INTO Coute
	VALUES (1, 30.5);


-- Creation de EstVoisine
-- Exterieur
INSERT INTO EstVoisine
	VALUES (1, 2);
INSERT INTO EstVoisine
	VALUES (2, 1);
INSERT INTO EstVoisine
	VALUES (1, 3);
INSERT INTO EstVoisine
	VALUES (3, 1);
INSERT INTO EstVoisine
	VALUES (2, 3);
INSERT INTO EstVoisine
	VALUES (3, 2);
-- Fenetre
INSERT INTO EstVoisine
	VALUES (4, 5);
INSERT INTO EstVoisine
	VALUES (5, 4);
INSERT INTO EstVoisine
	VALUES (4, 6);
INSERT INTO EstVoisine
	VALUES (6, 4);
INSERT INTO EstVoisine
	VALUES (5, 7);
INSERT INTO EstVoisine
	VALUES (7, 5);
INSERT INTO EstVoisine
	VALUES (6, 7);
INSERT INTO EstVoisine
	VALUES (7, 6);
-- Cuisine
INSERT INTO EstVoisine
	VALUES (8, 9);
INSERT INTO EstVoisine
	VALUES (9, 8);
INSERT INTO EstVoisine
	VALUES (8, 11);
INSERT INTO EstVoisine
	VALUES (11, 8);
INSERT INTO EstVoisine
	VALUES (9, 10);
INSERT INTO EstVoisine
	VALUES (10, 9);
INSERT INTO EstVoisine
	VALUES (10, 12);
INSERT INTO EstVoisine
	VALUES (12, 10);
INSERT INTO EstVoisine
	VALUES (11, 12);
INSERT INTO EstVoisine
	VALUES (12, 11);


-- Creation de ContientPlat
INSERT INTO ContientPlat
	VALUES ('PETITE FAIM', 'SALADE COMPLETE');
INSERT INTO ContientPlat
	VALUES ('PETITE FAIM', 'PAVET CABILLAUD');
INSERT INTO ContientPlat
	VALUES ('GROSSE FAIM', 'CIVET SANGLIER');
INSERT INTO ContientPlat
	VALUES ('GROSSE FAIM', 'MOULES FRITES');
INSERT INTO ContientPlat
	VALUES ('GROSSE FAIM', 'GRATIN RAVIOLES');


-- Creation de ContientAutreArticle
-- Petite Faim
INSERT INTO ContientAutreArticle
	VALUES ('PETITE FAIM', 'SALADE FRUITS');
-- Boissons
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'BIERE');
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'ARCENS');
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'KIR CHATAIGNE');
-- Entrees
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'SALADE RAVIOLES');
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'SALADE CAILLETTE');
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'FOIE GRAS');
-- Desserts
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'MARRONS GLACES');
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'PROFITEROLES');
INSERT INTO ContientAutreArticle
	VALUES ('GROSSE FAIM', 'GLACES 2 BOULES');


-- Creation EstElement
-- Première carte
INSERT INTO EstElement
	VALUES ('PETITE FAIM', 1, 12.0);
INSERT INTO EstElement
	VALUES ('CAFE', 1, 1.50);
INSERT INTO EstElement
	VALUES ('ARCENS', 1, 2.0);
INSERT INTO EstElement
	VALUES ('COCA', 1, 2.0);
INSERT INTO EstElement
	VALUES ('FOIE GRAS', 1, 5.0);
-- Deuxième carte
INSERT INTO EstElement
	VALUES ('GROSSE FAIM', 2, 18.50);
INSERT INTO EstElement
	VALUES ('COCA', 2, 2.0);
-- Troisième carte
INSERT INTO EstElement
	VALUES ('PETITE FAIM', 3, 12.0);
INSERT INTO EstElement
	VALUES ('GROSSE FAIM', 3, 18.50);
INSERT INTO EstElement
	VALUES ('SALADE FRUITS', 1, 3.0);


-- Creation des commandes
INSERT INTO Commande
	VALUES (1, 'PETITE FAIM', 1);
INSERT INTO Commande
	VALUES (1, 'GROSSE FAIM', 1);


