package GraphicFrames;

import Modele.*;
import java.sql.*;
import java.util.Date;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trentini
 */
public class FrameReservationList extends javax.swing.JFrame {

    ListReservations ReservationList;
    
    /**
     * Creates new form FrameReservationList
     */
    public FrameReservationList() {
        initComponents();
        
        this.ReservationList = new ListReservations();
        
        ListTables CodesTables = new ListTables();
        CodesTables.add(2); CodesTables.add(5); CodesTables.add(6); CodesTables.add(15);
        
        this.ReservationList.addReservation(new Reservation(CodesTables, 12, "Nome ABC", "123456", (Date) new Date(2016, 11, 20, 15, 30), Service.Midday));
        this.ReservationList.addReservation(new Reservation(new ListTables(), 12, "Nome ABC", "123456", (Date) new Date(2016, 11, 20, 15, 30), Service.Midday));
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Date");
        model.addColumn("Name");
        model.addColumn("Phone");
        model.addColumn("# People");
        model.addColumn("Table(s)");
        
        this.ReservationsTable.setModel(model);
        
        for(Reservation r : this.ReservationList.getListReservations()){
            String day   = ( r.getJour().getDate() <= 10 ) ? ("0"+r.getJour().getDate()) : (""+r.getJour().getDate());
            String month = ( r.getJour().getMonth()+1 <= 10) ? ("0"+(r.getJour().getMonth()+1)) : (""+(r.getJour().getMonth()+1));
            
            model.addRow(new Object[]{ day + " / " + month, r.getNomClient(), r.getTel(), r.getNbPersonnes(), r.getCodeTable() });
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReservationsTable = new javax.swing.JTable();
        OpenSelectedReservation = new javax.swing.JButton();
        DeleteSelectedReservation = new javax.swing.JButton();
        AddNewReservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WindowTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        WindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WindowTitle.setText("Reservations List");

        ReservationsTable.setModel(new DefaultTableModel());
        ReservationsTable.setColumnSelectionAllowed(true);
        ReservationsTable.setRowHeight(30);
        ReservationsTable.getTableHeader().setReorderingAllowed(false);
        ReservationsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservationsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReservationsTable);
        ReservationsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        OpenSelectedReservation.setText("Open Selected Reservation");
        OpenSelectedReservation.setActionCommand("Open Reservation #??");
        OpenSelectedReservation.setEnabled(false);
        OpenSelectedReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenSelectedReservationActionPerformed(evt);
            }
        });

        DeleteSelectedReservation.setText("Delete Selected Reservation");
        DeleteSelectedReservation.setEnabled(false);
        DeleteSelectedReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSelectedReservationActionPerformed(evt);
            }
        });

        AddNewReservation.setText("Add New Reservation");
        AddNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(WindowTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddNewReservation)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteSelectedReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(OpenSelectedReservation)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(WindowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSelectedReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenSelectedReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenSelectedReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenSelectedReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenSelectedReservationActionPerformed

    private void DeleteSelectedReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSelectedReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteSelectedReservationActionPerformed

    private void AddNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewReservationActionPerformed

    private void ReservationsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsTableMouseClicked
        //this.ReservationsList.getValueAt(this.ReservationsList.getSelectedRow(), )
    }//GEN-LAST:event_ReservationsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReservationList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewReservation;
    private javax.swing.JButton DeleteSelectedReservation;
    private javax.swing.JButton OpenSelectedReservation;
    private javax.swing.JTable ReservationsTable;
    private javax.swing.JLabel WindowTitle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
