package GraphicFrames;

import Modele.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trentini
 */
public class ViewReservationList extends AbstractView {

    private static ViewReservationList Window = null;
    private ControllerGraphic GC = null;
    
    private ListReservations ListReservs;
    private Reservation SelectedReservation;
    
    /**
     * Creates new form FrameReservationList
     */
    public ViewReservationList() {
        initComponents();
        
        this.ListReservs = ListReservations.singletonListReservations();
        
        ///*   TEST CODE
        ListTables CodesTables = new ListTables();
        CodesTables.add(2);
        CodesTables.add(5);
        CodesTables.add(6);
        CodesTables.add(15);

        this.ListReservs.addReservation(new Reservation(CodesTables, 12, "BB", "123456", new ReservationDate(2016, 11, 20, 15, 30), Service.Midday));
        this.ListReservs.addReservation(new Reservation(new ListTables(), 5, "AA", "123456", new ReservationDate(2016, 10, 5, 15, 30), Service.Midday));
        this.ListReservs.addReservation(new Reservation(new ListTables(), 500, "CC", "123456", new ReservationDate(2016, 11, 2, 15, 30), Service.Midday));
        //*/   END OF TEST CODE
        
        updateReservationTable();
    }
    
    public static ViewReservationList singletonFrameReservationList(){
        if(ViewReservationList.Window == null){
            ViewReservationList.Window = new ViewReservationList();
        }
        return ViewReservationList.Window;
    }
        
    @Override
    public void addController(AbstractControllerGraphic c) {
        this.GC = (ControllerGraphic) c;
    }
    
    private void updateReservationTable(){
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;   //all cells false
            }
        };

        model.addColumn("Date");
        model.addColumn("Name");
        model.addColumn("Phone");
        model.addColumn("# People");
        model.addColumn("Table(s)");

        this.ReservationsTable.setModel(model);
        for (Reservation r : this.ListReservs.getList()) {
            model.addRow(new Object[]{r.getDate().writeDateSortable(), r.getNomClient(), r.getPhone(), r.getNbPersonnes(), r.getCodeTable()});
        }
        
        setReservationTableSortable(model);
    }
    
    private void setReservationTableSortable(DefaultTableModel model){
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(this.ReservationsTable.getModel());
        this.ReservationsTable.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        
        sortKeys.add(new RowSorter.SortKey(model.findColumn("Name"), SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        
        int unsortableColumn;
        
        unsortableColumn = model.findColumn("# People");
        if(unsortableColumn != -1){
            sorter.setSortable(unsortableColumn, false);
        }
        
        unsortableColumn = model.findColumn("Table(s)");
        if(unsortableColumn != -1){
            sorter.setSortable(unsortableColumn, false);
        }
        
        sorter.sort();
    }
    
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if(b) updateReservationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowTitle = new javax.swing.JLabel();
        PaneOfReservationTable = new javax.swing.JScrollPane();
        ReservationsTable = new javax.swing.JTable();
        OpenSelectedReservation = new javax.swing.JButton();
        DeleteSelectedReservation = new javax.swing.JButton();
        AddNewReservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WindowTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        WindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WindowTitle.setText("Reservations List");

        ReservationsTable.setModel(new DefaultTableModel());
        ReservationsTable.setRowHeight(30);
        ReservationsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ReservationsTable.getTableHeader().setReorderingAllowed(false);
        ReservationsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReservationsTableMousePressed(evt);
            }
        });
        PaneOfReservationTable.setViewportView(ReservationsTable);
        ReservationsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        OpenSelectedReservation.setText("Open Selected Reservation");
        OpenSelectedReservation.setActionCommand("Open Reservation #??");
        OpenSelectedReservation.setEnabled(false);
        OpenSelectedReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenSelectedReservationActionPerformed(evt);
            }
        });

        DeleteSelectedReservation.setText("Delete Selected Reservation");
        DeleteSelectedReservation.setEnabled(false);
        DeleteSelectedReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSelectedReservationActionPerformed(evt);
            }
        });

        AddNewReservation.setText("Add New Reservation");
        AddNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaneOfReservationTable)
                    .addComponent(WindowTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddNewReservation)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteSelectedReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(OpenSelectedReservation)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(WindowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PaneOfReservationTable, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSelectedReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenSelectedReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenSelectedReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenSelectedReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenSelectedReservationActionPerformed

    private void DeleteSelectedReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSelectedReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteSelectedReservationActionPerformed

    private void AddNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewReservationActionPerformed
        GC.buttonAddNewReservation();
    }//GEN-LAST:event_AddNewReservationActionPerformed

    private void ReservationsTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsTableMousePressed
        if(this.ReservationsTable.getSelectedRow() == -1){
            this.DeleteSelectedReservation.setEnabled(false);
            this.OpenSelectedReservation.setEnabled(false);
        }else{
            this.SelectedReservation = this.ListReservs.getList().get(this.ReservationsTable.getSelectedRow());
            this.DeleteSelectedReservation.setEnabled(true);
            this.OpenSelectedReservation.setEnabled(true);
        }
    }//GEN-LAST:event_ReservationsTableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReservationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReservationList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewReservation;
    private javax.swing.JButton DeleteSelectedReservation;
    private javax.swing.JButton OpenSelectedReservation;
    private javax.swing.JScrollPane PaneOfReservationTable;
    private javax.swing.JTable ReservationsTable;
    private javax.swing.JLabel WindowTitle;
    // End of variables declaration//GEN-END:variables
}

