
package GraphicPackage;

import InterfaceMVC.Exceptions.*;
import Modele.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author trentini
 */
public class FrameCommande extends javax.swing.JFrame implements WindowView {

    private FrameReservationDetails windowReservationDetails;
    
    private int codeCarte = 1;
    private Article selectedMenu;
    private Commande thisCommande;

    public Commande getThisCommande() {
        return thisCommande;
    }

    public int getCodeCarte() {
        return codeCarte;
    }

    public Article getSelectedMenu() {
        return selectedMenu;
    }

    /**
     * Creates new form FrameCommande
     */
    public FrameCommande(FrameReservationDetails windowReservationDetails) {
        initComponents();
        
        this.windowReservationDetails = windowReservationDetails;
        this.windowReservationDetails.setEnabled(false);    //the old window is set to disabled (it means we can reactivate the window the next time it is set)
        
        this.thisCommande = new Commande(windowReservationDetails.getReservationCode(), new String(), new ArrayList<Article>());

        this.TextCodeReservation.setText("Reservation #" + this.thisCommande.getCodeReservation());
        
        updateCarte(codeCarte);
    }
    
    private void updateCarte(int codeCarte) {
        for(TypeArticle type : TypeArticle.values()){
            LinkedHashMap<String, Object> tableMap = new LinkedHashMap<>();
            
            for(Article a : GlobalGraphicView.singletonGlobalGraphicView().getController().getArticles(codeCarte, type)){
                tableMap.put(a.getName(), a);
            }
            
            TableModel model = new SpecialJavaTableModel(tableMap, Article.class);
            
            switch(type){
                case ENTREE:    this.Entrees.setModel(model);    break;
                case BOISSON:   this.Boissons.setModel(model);   break;
                case PLAT:      this.Plats.setModel(model);      break;
                case DESSERT:   this.Desserts.setModel(model);   break;
                case MENU:      this.Menus.setModel(model);      break;
            }
        }
    }
    
    private void updateCommande(){
        LinkedHashMap<String, Object> tableMap = new LinkedHashMap<>();

        for(Article a : this.thisCommande.getListArticles()){
            tableMap.put(a.getName(), a);
        }

        TableModel model = new SpecialJavaTableModel(tableMap, Article.class);
        
        this.SelectedArticlesTable.setModel(model);
    }

    @Override
    public void dispose() {
        GlobalGraphicView.singletonGlobalGraphicView().showView(windowReservationDetails);
        super.dispose();
    }
     
    @Override
    public void update(Observable o, Object o1) {
        updateCarte(codeCarte);
        updateCommande();
    }

    @Override
    public boolean isSingleton() {
        return false;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SelectedArticlesTable = new javax.swing.JTable();
        ButtonDeleteSelectedArticle = new javax.swing.JButton();
        WindowTitle = new javax.swing.JLabel();
        ButtonFinishThisCommande = new javax.swing.JButton();
        ButtonAddSelectedArticle = new javax.swing.JButton();
        TabsArticlesTypes = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Entrees = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Plats = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Desserts = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Boissons = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        Menus = new javax.swing.JTable();
        FieldClientIdentifier = new javax.swing.JTextField();
        LabelCommandeIdentifier = new javax.swing.JLabel();
        TextCodeReservation = new javax.swing.JLabel();
        LabelCommandeIdentifier1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurant BDCO - Nouvelle Commande");

        SelectedArticlesTable.setModel(new DefaultTableModel());
        SelectedArticlesTable.setRowHeight(30);
        SelectedArticlesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SelectedArticlesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(SelectedArticlesTable);
        SelectedArticlesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        ButtonDeleteSelectedArticle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modele/Icons/minus-button.png"))); // NOI18N
        ButtonDeleteSelectedArticle.setText("Supprimer Article Selectioné");
        ButtonDeleteSelectedArticle.setToolTipText("");
        ButtonDeleteSelectedArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteSelectedArticleActionPerformed(evt);
            }
        });

        WindowTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        WindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WindowTitle.setText("Nouvelle Commande");

        ButtonFinishThisCommande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modele/Icons/database--arrow.png"))); // NOI18N
        ButtonFinishThisCommande.setText("Créer Nouvelle Commande");
        ButtonFinishThisCommande.setToolTipText("");
        ButtonFinishThisCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFinishThisCommandeActionPerformed(evt);
            }
        });

        ButtonAddSelectedArticle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modele/Icons/plus-button.png"))); // NOI18N
        ButtonAddSelectedArticle.setText("Ajouter Article Selectioné");
        ButtonAddSelectedArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddSelectedArticleActionPerformed(evt);
            }
        });

        Entrees.setModel(new DefaultTableModel());
        Entrees.setRowHeight(30);
        Entrees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Entrees.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Entrees);
        Entrees.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        TabsArticlesTypes.addTab("ENTREE", jScrollPane2);

        Plats.setModel(new DefaultTableModel());
        Plats.setRowHeight(30);
        Plats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Plats.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(Plats);
        Plats.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        TabsArticlesTypes.addTab("PLAT", jScrollPane3);

        Desserts.setModel(new DefaultTableModel());
        Desserts.setRowHeight(30);
        Desserts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Desserts.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(Desserts);
        Desserts.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        TabsArticlesTypes.addTab("DESSERT", jScrollPane4);

        Boissons.setModel(new DefaultTableModel());
        Boissons.setRowHeight(30);
        Boissons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Boissons.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(Boissons);
        Boissons.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        TabsArticlesTypes.addTab("BOISSON", jScrollPane5);

        Menus.setModel(new DefaultTableModel());
        Menus.setRowHeight(30);
        Menus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Menus.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(Menus);
        Menus.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        TabsArticlesTypes.addTab("MENU", jScrollPane6);

        FieldClientIdentifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FieldClientIdentifier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldClientIdentifier.setText(Calendar.getInstance().getTime().toString());

        LabelCommandeIdentifier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelCommandeIdentifier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCommandeIdentifier.setText("Identifiant de la");

        TextCodeReservation.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        TextCodeReservation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextCodeReservation.setText("# ????");

        LabelCommandeIdentifier1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelCommandeIdentifier1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCommandeIdentifier1.setText("Commande:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCommandeIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelCommandeIdentifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldClientIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TabsArticlesTypes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ButtonAddSelectedArticle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                            .addComponent(ButtonDeleteSelectedArticle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonFinishThisCommande, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WindowTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCodeReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WindowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCodeReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabsArticlesTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonAddSelectedArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(ButtonDeleteSelectedArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelCommandeIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelCommandeIdentifier1)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonFinishThisCommande, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldClientIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFinishThisCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFinishThisCommandeActionPerformed
        if(this.SelectedArticlesTable.getRowCount() > 0) {
            this.thisCommande.setIdentifier(this.FieldClientIdentifier.getText());
            GlobalGraphicView.singletonGlobalGraphicView().getController().addCommande(this.thisCommande);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this.getParent(), new NewCommandeException().getMessage());
        }
    }//GEN-LAST:event_ButtonFinishThisCommandeActionPerformed

    private void ButtonAddSelectedArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddSelectedArticleActionPerformed
        Article a = null;
        TableModel table = null;
        int row = -1;
        
        switch (TypeArticle.valueOf(this.TabsArticlesTypes.getTitleAt(this.TabsArticlesTypes.getSelectedIndex()))) {
            case ENTREE:  table = this.Entrees.getModel();  row = this.Entrees.getSelectedRow();  break;
            case PLAT:    table = this.Plats.getModel();    row = this.Plats.getSelectedRow();    break;
            case DESSERT: table = this.Desserts.getModel(); row = this.Desserts.getSelectedRow(); break;
            case BOISSON: table = this.Boissons.getModel(); row = this.Boissons.getSelectedRow(); break;
            case MENU:    table = this.Menus.getModel();    row = this.Menus.getSelectedRow();    break;
        }
        if(row >= 0){
            a = (Article) ((SpecialJavaTableModel) table).getObjectAt(row);

            if(a.getType().equals(TypeArticle.MENU) && this.thisCommande.getRegroupeArticle().keySet().contains(a.getName())){
                JOptionPane.showMessageDialog(this.getParent(), new MenuAlreadyAddedException().getMessage());
            }else{
                GlobalGraphicView.singletonGlobalGraphicView().getController().addArticleCommande(a, this.thisCommande);
                a.setQuantity(this.thisCommande.getRegroupeArticle().get(a.getName()));

                if (a.getType().equals(TypeArticle.MENU)) {
                    this.selectedMenu = a;
                    WindowView frameMenu = new FrameMenu(this);
                    GlobalGraphicView.singletonGlobalGraphicView().showView(frameMenu);
                }
            }
        }
        
        this.updateCommande();
    }//GEN-LAST:event_ButtonAddSelectedArticleActionPerformed

    private void ButtonDeleteSelectedArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteSelectedArticleActionPerformed
        if(this.SelectedArticlesTable.getSelectedRow() >= 0){
            Article a = (Article) ((SpecialJavaTableModel) this.SelectedArticlesTable.getModel()).getObjectAt(this.SelectedArticlesTable.getSelectedRow());
            
            if (a.getQuantity()-1 != 0) {
                GlobalGraphicView.singletonGlobalGraphicView().getController().removeArticleCommande(a, this.thisCommande);
                a.setQuantity(this.thisCommande.getRegroupeArticle().get(a.getName()));
            }else{
                GlobalGraphicView.singletonGlobalGraphicView().getController().removeArticleCommande(a, this.thisCommande);
                a.setQuantity(1);
                if (a.getType().equals(TypeArticle.MENU)) {
                    ((Menu) a).restartArticlesInMenu();
                }
            }
        }
        this.updateCommande();
    }//GEN-LAST:event_ButtonDeleteSelectedArticleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Boissons;
    private javax.swing.JButton ButtonAddSelectedArticle;
    private javax.swing.JButton ButtonDeleteSelectedArticle;
    private javax.swing.JButton ButtonFinishThisCommande;
    private javax.swing.JTable Desserts;
    private javax.swing.JTable Entrees;
    private javax.swing.JTextField FieldClientIdentifier;
    private javax.swing.JLabel LabelCommandeIdentifier;
    private javax.swing.JLabel LabelCommandeIdentifier1;
    private javax.swing.JTable Menus;
    private javax.swing.JTable Plats;
    private javax.swing.JTable SelectedArticlesTable;
    private javax.swing.JTabbedPane TabsArticlesTypes;
    private javax.swing.JLabel TextCodeReservation;
    private javax.swing.JLabel WindowTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
