package GraphicPackage;

import InterfaceMVC.EnumView;
import InterfaceMVC.Exceptions.*;
import Modele.*;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author trentini
 */
public class FrameReservationList extends javax.swing.JFrame implements WindowView{

    final private static FrameReservationList singletonWindow = new FrameReservationList();
    
    private int selectedReservationCode;

    public int getSelectedReservationCode() {
        return selectedReservationCode;
    }
    
    /**
     * Creates new form FrameReservationList
     */
    private FrameReservationList() {
        initComponents();
        updateReservationTable(GlobalGraphicView.singletonGlobalGraphicView().getController().getReservationList());
    }
    
    public static FrameReservationList singletonFrameReservationList(){
        return FrameReservationList.singletonWindow;
    }
    
    @Override
    public void update(Observable o, Object arg) {
        updateReservationTable(GlobalGraphicView.singletonGlobalGraphicView().getController().getReservationList());
    }
    
    @Override
    public void dispose(){
        if(SingletonListCommande.singletonListCommande().isEmpty()){
            super.dispose();    // If the list of Commandes is empty, so the application can be closed
        }else{
            // If the list of Commandes is not empty, it means there are commandes in need of payment 
            JOptionPane.showMessageDialog(this.getParent(), new CommandesNotSaved().getMessage());
        }
    }
    
    @Override
    public boolean isSingleton(){
        return true;
    }
    
    private void updateReservationTable(ArrayList<Reservation> listReservations){
        LinkedHashMap<String, Object> tableMap = new LinkedHashMap<>();
        for (Reservation r : listReservations) {
            tableMap.put(Integer.toString(r.getCodeReservation()), r);
        }
        
        TableModel model = new SpecialJavaTableModel(tableMap, Reservation.class);
        
        this.ReservationsTable.setModel(model);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model) {
            @Override
            public boolean isSortable(int column) {
                if (column <= 3) {
                    return true;
                } else {
                    return false;
                }
            }
        ;
        };
        this.ReservationsTable.setRowSorter(sorter);
        
        //this.ReservationsTable.setAutoCreateRowSorter(true);

        try{
            this.ReservationsTable.getColumnModel().getColumn(0).setMaxWidth(60);
            this.ReservationsTable.getColumnModel().getColumn(3).setMaxWidth(200);
            this.ReservationsTable.getColumnModel().getColumn(4).setMaxWidth(60);
            this.ReservationsTable.getColumnModel().getColumn(5).setMaxWidth(60);
            
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            this.ReservationsTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        }catch(Exception e){}
    }
    
    
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
    }
    
    private void updateSelectedReservation(){
        if(this.ReservationsTable.getSelectedRow() == -1){
            this.OpenSelectedReservation.setEnabled(false);
        }else{
            this.selectedReservationCode = Integer.valueOf(((String)this.ReservationsTable.getValueAt(this.ReservationsTable.getSelectedRow(), 0)).replace(".", ""));
            this.OpenSelectedReservation.setEnabled(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WindowTitle = new javax.swing.JLabel();
        PaneOfReservationTable = new javax.swing.JScrollPane();
        ReservationsTable = new javax.swing.JTable();
        OpenSelectedReservation = new javax.swing.JButton();
        AddNewReservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurant BDCO - Liste de Réservations");

        WindowTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        WindowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WindowTitle.setText("Liste de Réservations");

        ReservationsTable.setModel(new DefaultTableModel());
        ReservationsTable.setRowHeight(30);
        ReservationsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ReservationsTable.getTableHeader().setReorderingAllowed(false);
        ReservationsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReservationsTableMousePressed(evt);
            }
        });
        ReservationsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReservationsTableKeyPressed(evt);
            }
        });
        PaneOfReservationTable.setViewportView(ReservationsTable);
        ReservationsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        OpenSelectedReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modele/Icons/book-open-next.png"))); // NOI18N
        OpenSelectedReservation.setText("Ouvrir Reservation Selectioné");
        OpenSelectedReservation.setToolTipText("");
        OpenSelectedReservation.setActionCommand("Open Reservation #??");
        OpenSelectedReservation.setEnabled(false);
        OpenSelectedReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenSelectedReservationActionPerformed(evt);
            }
        });

        AddNewReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modele/Icons/book--plus.png"))); // NOI18N
        AddNewReservation.setText("Ajouter Reservation");
        AddNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaneOfReservationTable, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(WindowTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OpenSelectedReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(WindowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PaneOfReservationTable, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenSelectedReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenSelectedReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenSelectedReservationActionPerformed
        GlobalGraphicView.singletonGlobalGraphicView().getController().setView(EnumView.ResevationDetails);
    }//GEN-LAST:event_OpenSelectedReservationActionPerformed

    private void AddNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewReservationActionPerformed
        GlobalGraphicView.singletonGlobalGraphicView().getController().setView(EnumView.ReservationCreation);
    }//GEN-LAST:event_AddNewReservationActionPerformed

    private void ReservationsTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsTableMousePressed
        this.updateSelectedReservation();
    }//GEN-LAST:event_ReservationsTableMousePressed

    private void ReservationsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReservationsTableKeyPressed
        this.updateSelectedReservation();
    }//GEN-LAST:event_ReservationsTableKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewReservation;
    private javax.swing.JButton OpenSelectedReservation;
    private javax.swing.JScrollPane PaneOfReservationTable;
    private javax.swing.JTable ReservationsTable;
    private javax.swing.JLabel WindowTitle;
    // End of variables declaration//GEN-END:variables
}

